### PR TITLE
Fix the encoding prob of Spybot history

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**
BB was for me with the encoding prob because of the special characters in "Spybot History" no more usable! So I needed to make a fix at least for me! @az0, if you don't have this encoding prob, at least everyone with the same codepage then me must have it and is therefor no more able to use BB! So if you will not role out a new version of WinApp2.ini in the next days, please use this pushed version and roll it out to the users!
Btw., side effect of the PR: As I'm a Windows user and line-endings get in this repo done be the normal settings, my PR fix also the line-endings and the empty line, that is normally between each entry! ;-)

### CODE REVIEW

**Comment by az0** [comment]
Please clarify what "fix the encoding" means. Did you just change the line endings? 

The line count changed
upstream: 20154 lines
mine:: 18018 lines 
yours: 17545 lines

The file is processed by a script, so I need to fix the script.

**Comment by Tobias-B-Besemer** [comment]
Someone used a special character as dash in Spybot history. This is fixed upstream since a long time. I fixed this now manual. Your script generates ATM ~500 empty lines between the lines with content.

**Comment by az0** [comment]
You said it was fixed upstream, so I pulled the new version from upstream using the update script.

**Comment by az0** [comment]
I tested the Winapp2.ini update, and it loads fine on my system. There are no errors.

**Comment by Tobias-B-Besemer** [comment]
Great work! I test it later, too!

**Comment by Tobias-B-Besemer** [comment]
> You said it was fixed upstream, so I pulled the new version from upstream using the update script.

I see no update in https://github.com/bleachbit/winapp2.ini ...

**Comment by az0** [comment]
It should show up soon

**Pull request closed without merging**
